export const statesOfIndia = [
	"andhra pradesh",
	"arunachal pradesh",
	"assam",
	"bihar",
	"chhattisgarh",
	"goa",
	"gujarat",
	"haryana",
	"himachal pradesh",
	"jharkhand",
	"karnataka",
	"kerala",
	"madhya pradesh",
	"maharashtra",
	"manipur",
	"meghalaya",
	"mizoram",
	"nagaland",
	"odisha",
	"punjab",
	"rajasthan",
	"sikkim",
	"tamil nadu",
	"telangana",
	"tripura",
	"uttarakhand",
	"uttar pradesh",
	"west bengal"
];